server:
  port: 8086
  servlet:
    context-path: /api

madie:
  allowedApi: http://localhost:9000
  cql-elm:
    service:
      base-url: ${ELM_TRANSLATOR_SERVICE_URL:http://localhost:8084/api}
      cql-elm-urn: /cql/elm
      cql-lookups: /cql/lookups
      relevant-data-elements: /cql/relevant-elements
  qrda:
    service:
      base-url: ${QRDA_SERVICE_URL:http://localhost:4567/api}
      qrda: /qrda

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-18092578.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}